### ISSUE TITLE
ML4 improvement records

### ISSUE THREAD

**Issue by Suraporn** [UBC-MDS/nba_player_stat#63]

**Comment by Suraporn** [comment]
Modification: Add two methods to use the app by clicking the fill and run R script
Source: Peer review milestone 3 - Question12 (https://github.ubc.ca/fdandrea/532-peer-review/issues/7#issuecomment-22991)
Team member: Florencia
Commit/s: https://github.com/UBC-MDS/nba_player_stat/commit/6403e85e8c83c26e1e2258131c11bf1ab3fdf929

**Comment by pengzh313** [comment]
Modification: Added dynamic UI element to automatically uncheck whole career when users update careeryearslider & team_select.
Source: Peer review milestone 3 - Question 9 [link](https://github.ubc.ca/fdandrea/532-peer-review/issues/7#issuecomment-22993)
Team member: Peng Zhang
Commit/s: [link](https://github.com/UBC-MDS/nba_player_stat/commit/9091ec6dbfb5eb6b4547a009af906321249ca224)

**Comment by pengzh313** [comment]
Modification: Added approximate string matching to NBA players name search bar
Source: TA feedback [link](https://github.com/UBC-MDS/nba_player_stat/issues/50#issue-1620364500) and Peer review milestone 3 - Question 13 [link](https://github.ubc.ca/fdandrea/532-peer-review/issues/7#issuecomment-22991)
Team member: Fujie Sun
Commit/s: [link1](https://github.com/UBC-MDS/nba_player_stat/commit/84552be5c8abd9a7de07753679552d42367945ae),[link2](https://github.com/UBC-MDS/nba_player_stat/commit/ef970a829f7da7ddde7fe9d98ab9201feaff11a2),[link3](https://github.com/UBC-MDS/nba_player_stat/commit/d196894e247dc16fd56857edb9c0e0d17ceb1099)

**Comment by pengzh313** [comment]
Modification: Added statistic selection drop down to provide users with options of checking individual metrics
Source: Peer review milestone 3 - Question 11 [link](https://github.ubc.ca/fdandrea/532-peer-review/issues/7#issuecomment-22993)
Team member: Fujie Sun
Commit/s: [link](https://github.com/UBC-MDS/nba_player_stat/commit/78c24e97bd3ffaa53dcb76445f8d5938724e48c0)

**Comment by pengzh313** [comment]
Modification: Improved visualization elements for plots
Source: TA feedback [link](https://github.com/UBC-MDS/nba_player_stat/issues/50#issue-1620364500), Peer review milestone 3 - Question 4 [link](https://github.ubc.ca/fdandrea/532-peer-review/issues/7#issuecomment-22994)
Team member: Chen Lin
Commit/s: [link1](https://github.com/UBC-MDS/nba_player_stat/commit/2ac0cf2e34ff7bf820706c863193f02420634de8), [link2](https://github.com/UBC-MDS/nba_player_stat/commit/8796e42c401263369caf67b9108bcf77683ac7e4), [link3](https://github.com/UBC-MDS/nba_player_stat/commit/734dad005f928319ecd1de18d4b09d41c289823d), [link4](https://github.com/UBC-MDS/nba_player_stat/commit/97babc9ad6c6d247b37c222005648bc2ed1eeddd), [link5](https://github.com/UBC-MDS/nba_player_stat/commit/76c97d05460e2d319fcee726839bcc22fff90bfd)
