### ISSUE TITLE
Add proper license

### ISSUE THREAD

**Issue by Suraporn** [UBC-MDS/nba_player_stat#8]
Hello guys,

Let's discuss on the license of our project. It seems like there are several licenses that we can use, more information in this link [https://choosealicense.com/]. Since for our project, we do not intend to make any profit nor other people making profit from our work, therefore, I think the MIT license works fine for us. The MIT license is short and simple permissive license with conditions only requiring preservation of copyright and license notices.

What do you think about our license? Any other ideas?
@CChCheChen @Althrun-sun @pengzh313

**Comment by CChCheChen** [comment]
I am good with the MIT license

**Comment by Althrun-sun** [comment]
I agree with the MIT license.

**Comment by pengzh313** [comment]
I agree with the MIT license for this project. There is no funding support or employment relationship pertaining to the project, and this is mostly for learning purposes. Also, by adopting MIT licence, it clearly states that there is no warranty from the authors including us and future contributors.

**Comment by Suraporn** [comment]
Ok, we are consensus to use the MIT license for our project.
